apiVersion: v1
kind: Service
metadata:
  name: inventory-api-svc
  namespace: inventory
spec:
  type: NodePort
  selector:
    app: inventory-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
